/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PING_H_RPCGEN
#define _PING_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define PROGRAMAPING 2000001
#define PING_VERSAO1 1

#if defined(__STDC__) || defined(__cplusplus)
#define PING_BACK 1
extern  int * ping_back_1(int *, CLIENT *);
extern  int * ping_back_1_svc(int *, struct svc_req *);
extern int programaping_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define PING_BACK 1
extern  int * ping_back_1();
extern  int * ping_back_1_svc();
extern int programaping_1_freeresult ();
#endif /* K&R C */
#define PING_VERSAO2 2

#if defined(__STDC__) || defined(__cplusplus)
extern  int * ping_back_2(int *, CLIENT *);
extern  int * ping_back_2_svc(int *, struct svc_req *);
extern int programaping_2_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
extern  int * ping_back_2();
extern  int * ping_back_2_svc();
extern int programaping_2_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PING_H_RPCGEN */
