/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"

int *
somar_1_svc(operando *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
    result = argp->x + argp->y;

	return &result;
}

int *
subtrair_1_svc(operando *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
    result = argp->x - argp->y;

	return &result;
}
